run:
  concurrency: 3
  timeout: 4m

linters:
  enable-all: true
  disable:
    - depguard
    - err113
    - execinquery
    - exhaustruct
    - exportloopref
    - funlen
    - gomnd
    - ireturn
    - mnd
    - varnamelen
    - wrapcheck
    - wsl

linters-settings:
