version: "2"
run:
  concurrency: 3
linters:
  default: all
  disable:
    - depguard
    - ireturn
    - mnd
    - varnamelen
    - unqueryvet
    - wrapcheck
    - wsl
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling

    rules:
      - path: _test\.go
        linters:
          - exhaustruct

formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  exclusions:
    generated: lax
