#!/bin/sh
# Run from any directory. Requires Git >= 2.54, GNU tar, gzip and sha256sum.
set -eu
umask 022

destination=$(CDPATH= cd -- "$(dirname -- "$0")/../.." && pwd)
scratch=$(mktemp -d)
trap 'rm -rf "$scratch"' EXIT HUP INT TERM
export GIT_CONFIG_NOSYSTEM=1 GIT_CONFIG_GLOBAL=/dev/null
export GIT_AUTHOR_NAME=Test GIT_AUTHOR_EMAIL=test@example.com
export GIT_COMMITTER_NAME=Test GIT_COMMITTER_EMAIL=test@example.com

version=$(git version | awk '{print $3}')
major=${version%%.*}
minor=${version#*.}
minor=${minor%%.*}
if [ "$major" -lt 2 ] || { [ "$major" -eq 2 ] && [ "$minor" -lt 54 ]; }; then
    echo 'Git 2.54 or later is required (SHA-256 and 256-base graph support).' >&2
    exit 1
fi

entries="$scratch/commit_graph_entries.go"
cat > "$entries" <<'EOF'
// Code generated by scripts/commitgraph/generate.sh; DO NOT EDIT.

package fixtures

// commitGraphEntries maps .git archive hashes to their expected commit, tree
// and parent IDs, ordered oldest first.
//
//nolint:gochecknoglobals
var commitGraphEntries = map[string][]CommitGraphEntry{
EOF

archive() {
    tag=$1
    count=$2
    git --git-dir="$repository" commit-graph verify
    git --git-dir="$repository" fsck --strict
    git --git-dir="$repository" -c core.commitGraph=false log --reverse --format='%H %T %P' |
        sed 's/ *$//' > "$scratch/commits"

    # Stabilize the container as well as the Git objects and graph bytes.
    tar --sort=name --mtime=@1700000000 --owner=0 --group=0 --numeric-owner \
        -cf "$scratch/git.tar" -C "$repository" .
    gzip -n -c "$scratch/git.tar" > "$scratch/git.tgz"
    checksum=$(sha256sum "$scratch/git.tgz" | awk '{print $1}')
    cp "$scratch/git.tgz" "$destination/data/git-$checksum.tgz"

    # Verify the actual archive, including its object format and refs.
    extracted="$scratch/extracted-$tag"
    mkdir "$extracted"
    tar -xzf "$scratch/git.tgz" -C "$extracted"
    git --git-dir="$extracted" commit-graph verify
    git --git-dir="$extracted" fsck --strict

    printf '\t"%s": {\n' "$checksum" >> "$entries"
    awk '{
        printf "\t\t{Hash: \"%s\", Tree: \"%s\", Parents: []string{", $1, $2
        for (i = 3; i <= NF; i++) printf "\"%s\",", $i
        print "}},"
    }' "$scratch/commits" >> "$entries"
    printf '\t},\n' >> "$entries"

    head=$(git --git-dir="$repository" rev-parse HEAD)
    printf '%s DotGitHash=%s Head=%s ObjectsCount=%s ObjectFormat=%s\n' \
        "$tag" "$checksum" "$head" "$((count + 1))" "$algorithm"
}

for algorithm in sha1 sha256; do
    for count in 3 257; do
        [ "$algorithm" != sha256 ] || [ "$count" != 257 ] || continue
        repository="$scratch/$algorithm-$count.git"
        git -c init.defaultBranch=main init -q --bare --template= \
            --object-format="$algorithm" "$repository"
        tree=$(git --git-dir="$repository" mktree < /dev/null)
        i=0
        while [ "$i" -lt "$count" ]; do
            export GIT_AUTHOR_DATE="$((1700000000 + i)) +0000"
            export GIT_COMMITTER_DATE="$GIT_AUTHOR_DATE"
            if [ "$i" -eq 0 ]; then
                commit=$(printf 'commit %s\n' "$i" | git --git-dir="$repository" commit-tree "$tree")
            else
                commit=$(printf 'commit %s\n' "$i" | git --git-dir="$repository" commit-tree "$tree" -p "$commit")
            fi
            git --git-dir="$repository" update-ref refs/heads/main "$commit"
            git --git-dir="$repository" commit-graph write --reachable --split=no-merge
            i=$((i + 1))
        done
        chain="$repository/objects/info/commit-graphs/commit-graph-chain"
        [ "$(wc -l < "$chain")" -eq "$count" ]
        if [ "$count" -eq 257 ]; then
            tip=$(tail -n 1 "$chain")
            graph="$repository/objects/info/commit-graphs/graph-$tip.graph"
            [ "$(od -An -tu1 -j7 -N1 "$graph" | tr -d ' ')" -eq 0 ]
            archive "commit-graph-chain-$algorithm-257" "$count"
        else
            archive "commit-graph-chain-$algorithm" "$count"
            git --git-dir="$repository" commit-graph write --reachable
            rm -rf "$repository/objects/info/commit-graphs"
            archive "commit-graph-$algorithm" "$count"
        fi
    done
done
printf '}\n' >> "$entries"
gofmt -w "$entries"
cp "$entries" "$destination/commit_graph_entries.go"
